updated dialog launch script to check if the command file is a symbolic link and refuse to launch. It does this twice. If that fails, also added -h to chmod to dereference the symlink if it somehow still is one and gets to that stage added overrideDefaultIfNill property to command line arguments to make life easier if an argument with a default value is passed as a command line argument but we want to specifically ignore it fixes #479 fixes #477

diff --git a/dialog/Package/pkgroot/usr/local/bin/dialog b/dialog/Package/pkgroot/usr/local/bin/dialog
--- a/dialog/Package/pkgroot/usr/local/bin/dialog
+++ b/dialog/Package/pkgroot/usr/local/bin/dialog
@@ -4,11 +4,13 @@ uid=$(id -u "$currentUser")
 dialogpath="/Library/Application Support/Dialog/Dialog.app"
 dialogbin="$dialogpath/Contents/MacOS/Dialog"
 commandfile=$(echo "$@" | awk -v pattern="--commandfile" '{for (i=0;i<=NF;i++) {if ($i==pattern) print $(i+1) }}')
-
+commandFileInUse=0
 echoerr() { echo "$@" 1>&2; }
 
-if [[ -z $commandfile ]]; then
+if [ -z $commandfile ]; then
     commandfile="/var/tmp/dialog.log"
+else
+    commandFileInUse=1
 fi
 
 # convenience function to run a command as the current user
@@ -29,28 +31,48 @@ runAsUser() {
   fi
 }
 
+# Check to see if the command file is a symbolic link and abort if it is
+if [ -L $commandfile ]; then
+    echo "WARNING: ${commandfile} is a symbolic link - aborting"
+    echo "Did someone try and symlink the command file to a different location?"
+    echo "${commandfile} is a symbolic link to $(readlink $commandfile)"
+    echo "If you want to use a different command file, specify it with the --commandfile option"
+    exit 1
+fi
+
 # Check to make sure we have a binary to run
 if [ ! -e "$dialogbin" ]; then
     echoerr "ERROR: Cannot find swiftDialog binary at $dialogbin"
     exit 255
 fi
 
+# check to see if the command file exists and create it if it doesn't
+if [ ! -e "$commandfile" ]; then
+    /usr/bin/touch "$commandfile"
+# check to see if the command file is writeable
+elif [ ! -r "$commandfile" ]; then
+    echoerr ""
+    echoerr "Warning: command file ${commandfile} is not readable by user $currentUser"
+    echoerr ""
+fi
+
 # If we're running as root, launch swiftDialog as the user.
 if [ $(id -u) -eq 0 ]; then
-    if [ -e $commandfile ]; then
-        # Remove the command file if it exists
-        # Addresses issues with local privilege escalation via insecure file system operations
-        # (the dialog app will create this file if it doesn't exist)
-        rm $commandfile
+    # check if the command file is a file and in use
+    if [ -f $commandfile ] && [ $commandFileInUse -eq 1 ]; then
+        # make sure the console user has read access to the command file
+        # we need to do this safely though in case something has replaced the command file with a symlink
+        if [ -L $commandfile ]; then
+            # this should be caught earlier in the script, but just in case
+            echoerr "ERROR: ${commandfile} is a symbolic link - aborting"
+            exit 1
+        fi
+        # make sure the console user has read access to the command file
+        # -h flag is used to dereference the symlink if it is one, which it shouldn't be but just in case, to be sure, you never know, etc.
+        /bin/chmod -h 666 "$commandfile"
     fi
     runAsUser "$dialogbin" "$@"
 else
-    # check to see if the command file exists is readable by the user
-    if [[ -e "$commandfile" ]] && [[ ! -r "$commandfile" ]]; then
-        echoerr ""
-        echoerr "Warning: command file ${commandfile} is not readable by user $currentUser"
-        echoerr ""
-        exit 255
-    fi
     "$dialogbin" "$@"
 fi
+
